#### STAGE ONE
FROM node:14.15.4-alpine3.12 AS node
RUN apk add make
WORKDIR /app
COPY package*.json \
  .editorconfig \
  .env \
  .eslintignore\
  .eslintrc \
  .prettierrc ./
RUN apk add make
COPY . ./

#### STAGE TWO
FROM node AS build
WORKDIR /app
COPY --from=node /app ./
RUN make install \
  && make build

#### STAGE THREE
FROM mhart/alpine-node:14
WORKDIR /app
COPY --from=build /app ./
EXPOSE 3000
CMD npm start
